package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-03-16T15:58:02.482+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "PublicIdentityServiceService", 
                  wsdlLocation = "file:/C:/Users/sh1/Desktop/carHome.wsdl",
                  targetNamespace = "http://service.office.autohome.com/") 
public class PublicIdentityServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.office.autohome.com/", "PublicIdentityServiceService");
    public final static QName PublicIdentityServicePort = new QName("http://service.office.autohome.com/", "PublicIdentityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/sh1/Desktop/carHome.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PublicIdentityServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/sh1/Desktop/carHome.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PublicIdentityServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PublicIdentityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicIdentityServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public PublicIdentityServiceService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public PublicIdentityServiceService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public PublicIdentityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns PublicIdentityService
     */
    @WebEndpoint(name = "PublicIdentityServicePort")
    public PublicIdentityService getPublicIdentityServicePort() {
        return super.getPort(PublicIdentityServicePort, PublicIdentityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicIdentityService
     */
    @WebEndpoint(name = "PublicIdentityServicePort")
    public PublicIdentityService getPublicIdentityServicePort(WebServiceFeature... features) {
        return super.getPort(PublicIdentityServicePort, PublicIdentityService.class, features);
    }

}
