
package wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-03-16T15:58:02.332+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class PublicIdentityService_PublicIdentityServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.office.autohome.com/", "PublicIdentityServiceService");

    private PublicIdentityService_PublicIdentityServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PublicIdentityServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PublicIdentityServiceService ss = new PublicIdentityServiceService(wsdlURL, SERVICE_NAME);
        PublicIdentityService port = ss.getPublicIdentityServicePort();  
        
        {
        System.out.println("Invoking checkSession...");
        String _checkSession_json = "{auth: 'YDXbJW2baITU3YNM', sessionId: 'abc'}";
        String _checkSession__return = port.checkSession(_checkSession_json);
        System.out.println("checkSession.result=" + _checkSession__return);


        }

        System.exit(0);
    }

}
