package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-03-16T15:58:02.473+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.office.autohome.com/", name = "PublicIdentityService")
@XmlSeeAlso({ObjectFactory.class})
public interface PublicIdentityService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkSession", targetNamespace = "http://service.office.autohome.com/", className = "wsdl.CheckSession")
    @WebMethod
    @ResponseWrapper(localName = "checkSessionResponse", targetNamespace = "http://service.office.autohome.com/", className = "wsdl.CheckSessionResponse")
    public String checkSession(
            @WebParam(name = "json", targetNamespace = "")
            String json
    );
}
